apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: retraced
        tier: api
    spec:
      imagePullSecrets:
        - name: quayio
      containers:
        - name: api
          image: quay.io/retracedhq/api:a14cb16
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_URI
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PORT
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DATABASE
            - name: SCYLLA_HOSTS
              valueFrom:
                secretKeyRef:
                  name: scylla
                  key: SCYLLA_HOSTS
            - name: SCYLLA_KEYSPACE
              valueFrom:
                secretKeyRef:
                  name: scylla
                  key: SCYLLA_KEYSPACE
            - name: SCYLLA_USER
              valueFrom:
                secretKeyRef:
                  name: scylla
                  key: SCYLLA_USER
            - name: SCYLLA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scylla
                  key: SCYLLA_PASSWORD
            - name: HMAC_SECRET_ADMIN
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: HMAC_SECRET_ADMIN
            - name: HMAC_SECRET_VIEWER
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: HMAC_SECRET_VIEWER
            - name: RETRACED_APP_BASE
              valueFrom:
                secretKeyRef:
                  name: retraced
                  key: RETRACED_APP_BASE
            - name: MANDRILL_KEY
              valueFrom:
                secretKeyRef:
                  name: mandrill
                  key: MANDRILL_KEY
            - name: ELASTICSEARCH_NODES
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: ELASTICSEARCH_NODES
            - name: DISQUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: disque
                  key: DISQUE_PASSWORD
            - name: DISQUE_NODES
              valueFrom:
                secretKeyRef:
                  name: disque
                  key: DISQUE_NODES
            - name: AUTH0_CLIENT_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0
                  key: AUTH0_CLIENT_DOMAIN
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0
                  key: AUTH0_CLIENT_ID
            - name: RETRACED_PUBLIC_SITE
              valueFrom:
                secretKeyRef:
                  name: retraced
                  key: RETRACED_PUBLIC_SITE
            - name: STATUSPAGEIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: statuspageio
                  key: token
            - name: BUGSNAG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bugsnag
                  key: API_TOKEN
            - name: BUGSNAG_STAGE
              valueFrom:
                secretKeyRef:
                  name: bugsnag
                  key: STAGE
