apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: retraced
        tier: api
    spec:
      containers:
        - name: api
          image: quay.io/retracedhq/api:29006f6
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PORT
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DATABASE
            - name: SCYLLA_HOSTS
              valueFrom:
                secretKeyRef:
                  name: scylla
                  key: SCYLLA_HOSTS
            - name: SCYLLA_KEYSPACE
              valueFrom:
                secretKeyRef:
                  name: scylla
                  key: SCYLLA_KEYSPACE
            - name: SCYLLA_USER
              valueFrom:
                secretKeyRef:
                  name: scylla
                  key: SCYLLA_USER
            - name: SCYLLA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scylla
                  key: SCYLLA_PASSWORD
            - name: HMAC_SECRET_ADMIN
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: HMAC_SECRET_ADMIN
            - name: HMAC_SECRET_VIEWER
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: HMAC_SECRET_VIEWER
            - name: RETRACED_APP_BASE
              valueFrom:
                secretKeyRef:
                  name: retraced
                  key: RETRACED_APP_BASE
            - name: MANDRILL_KEY
              valueFrom:
                secretKeyRef:
                  name: mandrill
                  key: MANDRILL_KEY
            - name: ELASTICSEARCH_NODES
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: ELASTICSEARCH_NODES
            - name: DISQUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: disque
                  key: DISQUE_PASSWORD
            - name: DISQUE_NODES
              valueFrom:
                secretKeyRef:
                  name: disque
                  key: DISQUE_NODES
      imagePullSecrets:
        - name: quayio