apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress  
  annotations:
    kubernetes.io/ingress.allow-http: "false"  
spec:
  tls:
    - secretName: app-keys
  backend:
    serviceName: app
    servicePort: 80