apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: retraced
        tier: processor
    spec:
      containers:
        - name: processor
          image: quay.io/retracedhq/processor:6b544ef
          command: ["./bin/processor"]
          args: ["cron"]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PORT
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DATABASE
            - name: DISQUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: disque
                  key: DISQUE_PASSWORD
            - name: DISQUE_NODES
              valueFrom:
                secretKeyRef:
                  name: disque
                  key: DISQUE_NODES
      imagePullSecrets:
        - name: quayio
